name: ESPHome Build Dashboard

on:
  push:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome==2026.6.5

      - name: Check configuration
        run: esphome config waveshare-dashboard.yaml

      - name: Build Dashboard
        run: esphome compile waveshare-dashboard.yaml

      - name: Show firmware files
        run: |
          echo "=== GOTOWE PLIKI BIN ==="
          find .esphome/build/waveshare-dashboard -type f -name "*.bin" -exec ls -lh {} \;

      - name: Upload complete firmware package
        uses: actions/upload-artifact@v4
        with:
          name: waveshare-dashboard-firmware
          path: |
            .esphome/build/waveshare-dashboard/.pioenvs/waveshare-dashboard/*.bin
          if-no-files-found: error
