name: ESPHome Build .bin

on:
  push:
    branches: [ main, master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: |
          pip install esphome

      - name: Build Firmware
        run: |
          esphome compile waveshare-dashboard.yaml

      - name: Upload factory firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware
          path: .esphome/build/waveshare-dashboard/.pioenvs/waveshare-dashboard/firmware.factory.bin